In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2907, 9067, 449, 1531],
 [2907, 9067, 449, 374],
 [2907, 5480, 449, 3277],
 [5771, 6773, 1022, 3407, 3994],
 [5771, 6773, 1022, 3407, 7441],
 [4362, 2907, 9783, 449, 8068],
 [6524, 7921, 3964, 3407]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [6]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2907 9067  449 1531]
 [   0    0    0    0 2907 9067  449  374]
 [   0    0    0    0 2907 5480  449 3277]
 [   0    0    0 5771 6773 1022 3407 3994]
 [   0    0    0 5771 6773 1022 3407 7441]
 [   0    0    0 4362 2907 9783  449 8068]
 [   0    0    0    0 6524 7921 3964 3407]]


In [7]:
## feature representation
dim=10

In [8]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2024-10-12 21:58:48.508999: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2024-10-12 21:58:48.509052: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2024-10-12 21:58:48.509064: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2024-10-12 21:58:48.509125: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-10-12 21:58:48.509152: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 61ms/step


2024-10-12 21:58:54.498376: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,
          0.01909763, -0.02860688, -0.01090167,  0.02769769,
          0.01150067, -0.00262585],
        [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,
          0.01909763, -0.02860688, -0.01090167,  0.02769769,
          0.01150067, -0.00262585],
        [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,
          0.01909763, -0.02860688, -0.01090167,  0.02769769,
          0.01150067, -0.00262585],
        [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,
          0.01909763, -0.02860688, -0.01090167,  0.02769769,
          0.01150067, -0.00262585],
        [-0.03437486, -0.02685769, -0.00423677, -0.01487073,
         -0.03898407,  0.03657565, -0.0391533 ,  0.0424375 ,
          0.0464691 ,  0.03364295],
        [ 0.00270305, -0.01339722,  0.04795574,  0.03480026,
         -0.01092733, -0.04798094, -0.02356139, -0.03108072,
          0.0013216 ,  0.0424222 ],
        [ 0.02596107, -0.0039386 , -0.00388429,  0.0

In [11]:
embedded_docs.shape

(7, 8)

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 2907, 9067,  449, 1531], dtype=int32)

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,  0.01909763,
        -0.02860688, -0.01090167,  0.02769769,  0.01150067, -0.00262585],
       [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,  0.01909763,
        -0.02860688, -0.01090167,  0.02769769,  0.01150067, -0.00262585],
       [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,  0.01909763,
        -0.02860688, -0.01090167,  0.02769769,  0.01150067, -0.00262585],
       [ 0.00279965, -0.02048382, -0.0185458 ,  0.0052597 ,  0.01909763,
        -0.02860688, -0.01090167,  0.02769769,  0.01150067, -0.00262585],
       [-0.03437486, -0.02685769, -0.00423677, -0.01487073, -0.03898407,
         0.03657565, -0.0391533 ,  0.0424375 ,  0.0464691 ,  0.03364295],
       [ 0.00270305, -0.01339722,  0.04795574,  0.03480026, -0.01092733,
        -0.04798094, -0.02356139, -0.03108072,  0.0013216 ,  0.0424222 ],
       [ 0.02596107, -0.0039386 , -0.00388429,  0.03230513,  0.01060619,
        -0.01670873,  0.04860891, -0.02443152